// Page references describe the existing six-page upload, not observed outcomes.
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const democracySource='https://oyqevsygintkjrkfbzpx.supabase.co/storage/v1/object/public/portfolio-media/redesign/24c7a756-be36-4fd8-9462-6ee980c54736.pdf';
export const democracyResource=c=>c.resources.find(r=>r.url===democracySource);
const knownPdfs = {
  '24c7a756-be36-4fd8-9462-6ee980c54736.pdf': 'democracy-lesson-plan.pdf',
  'mock-election-evm-activity.pdf': 'mock-election-evm-activity.pdf',
  'mock-election-class8-poster.pdf': 'mock-election-class8-poster.pdf',
  'roots-to-wings-iks-presentation.pdf': 'roots-to-wings-iks-presentation.pdf',
  'notice-writing-english-pedagogy.pdf': 'notice-writing-english-pedagogy.pdf',
  'amity-ntcc-community-work-report.pdf': 'amity-ntcc-community-work-report.pdf',
  'ukg-assessment-test.pdf': 'ukg-assessment-test.pdf',
};
export function documentUrl(url,base) {
  if(!url) return '';
  if(url.startsWith('https://krishnamahato704-spec.github.io/E-portfolio/')) return base+url.split('/E-portfolio/')[1];
  if(url===democracySource)return base+'assets/democracy-lesson-plan.pdf';
  if(url.startsWith('./assets/')||url.startsWith('assets/')) return base + url.replace(/^\.?\//, '');
  for(const [key, file] of Object.entries(knownPdfs)) {
    if(url.includes(key)) return base + 'assets/' + file;
  }
  try {const parsed=new URL(url);return parsed.protocol==='https:'?parsed.href:'';}catch{return '';}
}
export function evidenceFeature(c,base,home=false) {
  const resource=democracyResource(c);if(!resource)return '';
  return `<section class="${home?'container section home-featured-artifact':'resource-feature'} evidence-feature" aria-labelledby="featured-design-title"><div class="feature-copy"><p class="eyebrow">Selected teaching evidence · Lesson plan</p><h2 id="featured-design-title">Democracy.<br><em>From questions to explanation.</em></h2><p class="lead">A dated Social Science plan for Class IX-B, with prior-knowledge questions, visual resources, discussion and assessment tasks.</p><p class="evidence-meta">25 July 2026 · 40 minutes · 6 pages</p><p>The plan records intended teaching and expected responses. Student work and completed reflection are not included.</p><div class="actions"><a class="button primary" href="${base}teaching/democracy/">Explore the lesson plan <span aria-hidden="true">↗</span></a><a class="text-link" href="${documentUrl(resource.url,base)}">Read the PDF <span aria-hidden="true">↗</span></a></div></div><figure class="evidence-preview"><a href="${base}teaching/democracy/"><img src="${base}assets/democracy-plan-preview.webp" width="900" height="636" loading="lazy" decoding="async" alt="First page of Democracy Lesson Plan No. 6, showing Class IX-B, date, duration and instructional approach"></a><figcaption>Original plan · page 1 of 6</figcaption></figure></section>`;
}
export function democracyView(c,base) {
  const resource=democracyResource(c);
  if(!resource)return `<div class="container page-heading"><h1>Democracy lesson plan</h1><p>This document is not currently published.</p><a class="text-link" href="${base}resources/">Browse teaching artifacts</a></div>`;
  const stages=[
    ['question','Context & intention','The shared learning intention', 'Pages 1–2', `<p>Lesson Plan No. 6 is an Amity University school-practicum plan for Social Science, Class IX-B, session 2026–27. It is dated 25 July 2026 and plans a 40-minute face-to-face lesson.</p><p>The objectives are to recall the meaning and features of democracy, distinguish forms of government, and explain the role of elections. The plan also identifies respect for different opinions and responsible citizenship.</p>`],
    ['explore','Prior knowledge','Begin with what learners know','Page 3', `<p>The opening questions ask learners to define democracy, identify Abraham Lincoln’s familiar definition, and recall monarchy, oligarchy and dictatorship. The plan connects previous learning about Sabha and Samiti to participation.</p><p>These are planned diagnostic questions. The listed student answers are expected responses, not a record of what a class actually said.</p>`],
    ['discuss','Explanation & discussion','Use visuals and questions','Pages 4–5', `<p>A concept diagram supports explanation of direct and indirect democracy and parliamentary and presidential systems. India and the United States provide a comparison.</p><p>Election and protest photographs support discussion of representation, accountability and citizen participation. The plan asks why elections recur and whether peaceful protest is necessary in democracy, allowing different viewpoints.</p>`],
    ['explain','Learner activity & support','Oral and written ways to respond','Pages 3–5', `<p>Learners are asked to recall, discuss, explain and complete written responses. Resources include a quotation visual, concept diagram, election and protest photographs, blackboard work and response sheets.</p><p>These provide more than one way to encounter and explain the idea. The document does not specify differentiated tasks, individual learning needs or targeted scaffolds. Documenting those choices is a next step in developing this plan.</p>`],
    ['assess','Assessment','Check for understanding','Pages 3 and 5', `<dl class="evidence-checks"><div><dt>Diagnostic</dt><dd>Recall democracy and other forms of government before the new explanation.</dd></div><div><dt>Guided practice</dt><dd>Define democracy, name three forms of government, and explain elections.</dd></div><div><dt>Independent practice</dt><dd>Explain the role of protest in ensuring accountability.</dd></div><div><dt>Evaluation</dt><dd>Give reasons for comparing democracy favourably with other forms of government.</dd></div></dl><p>The file contains prompts, not completed response sheets, marking criteria or feedback. It supports a review of assessment planning; it does not establish student progress.</p>`],
    ['reflect','Reflection & next evidence','Reflect and adjust','Page 6', `<p>The final page asks what engaged students, which concepts needed another explanation, how students responded, and what should change next time. The reflection, supervisor remarks and signature fields are blank.</p><p>A completed reflection would connect one observed response to a specific teaching change. An anonymised response sheet and mentor feedback would allow a reviewer to assess that connection.</p>`]
  ];
  return `<div class="container democracy-page"><header class="page-heading"><p class="eyebrow">Teaching artifact · Planning evidence</p><h1>Democracy.<br><em>A lesson in detail.</em></h1><p class="lead">Class IX-B · Social Science · 25 July 2026</p><p>This is planning evidence, not a report of a delivered lesson.</p><div class="actions"><a class="button primary" href="${documentUrl(resource.url,base)}">Read lesson plan PDF · 6 pages</a><a class="text-link" href="${escape(resource.url)}" target="_blank" rel="noopener noreferrer">Original upload <span class="sr-only">(new tab)</span> ↗</a></div></header><div class="democracy-layout"><aside class="democracy-sticky-col"><div class="planning-lens-card"><div class="planning-lens-header"><p class="eyebrow">Evidence guide</p><div class="democracy-local-progress"><span>Section</span><span id="democracy-stage-counter"><span class="active-stage-num">01</span> / 06</span></div></div><h2>Read the plan.<br>Follow the evidence.</h2><p class="small">40 minutes · Face-to-face · Session 2026–27</p><div class="active-stage-status-strip"><span id="democracy-active-stage-label">01 / Context & intention</span></div><div class="truth-notice"><p class="small">The lesson plan is available. Completed student work and supervisor feedback are not included.</p></div><div class="democracy-nav-track-wrap"><div class="democracy-vertical-rule" aria-hidden="true"><div class="democracy-vertical-fill" id="democracy-progress-bar"></div></div><nav class="democracy-stage-nav" aria-label="Lesson evidence sections"><ol>${stages.map(([id,label],i)=>`<li><a href="#stage-${id}" class="stage-nav-item"><span class="st-num">${String(i+1).padStart(2,'0')}</span><span class="st-name">${label}</span></a></li>`).join('')}</ol></nav></div></div></aside><article class="democracy-story-col prose">${stages.map(([id,label,title,pages,body],i)=>`<section id="stage-${id}" class="democracy-stage" data-stage-index="${i+1}"><div class="stage-header"><span class="stage-badge">STAGE ${String(i+1).padStart(2,'0')}</span><p class="eyebrow">${label}</p></div><h2>${title}</h2>${body}<a class="text-link evidence-page-link" href="${documentUrl(resource.url,base)}#page=${id==='question'?1:id==='explore'?3:id==='discuss'?4:id==='explain'?3:id==='assess'?5:6}">${pages} in the original plan ↗</a></section>`).join('')}</article></div><section class="democracy-continuation-bridge"><div class="continuation-meta"><span class="continuation-tag">NEXT CHAPTER / 04</span><h2>Teacher’s Resource Library</h2><p>Browse the published teaching files.</p></div><a class="button secondary" href="${base}resources/">Explore Teaching Resources ↗</a></section></div>`;
}
