import {studySummary,recruiterFacts} from './recruiter.js?v=recruiter-20260912';
import {defaultContent} from './content.js?v=recruiter-20260912';
export const routes={
  home:{path:'',title:'History & Social Science Educator',nav:'Home'},
  profile:{path:'profile/',title:'Profile & Education',nav:'Profile'},
  teaching:{path:'teaching/',title:'Teaching Journey',nav:'Teaching'},
  resources:{path:'resources/',title:'Teaching Resources',nav:'Resources'},
  credentials:{path:'credentials/',title:'Credentials & Presentations',nav:'Credentials'},
  contact:{path:'contact/',title:'Contact',nav:'Contact'},
  resume:{path:'resume/',title:'Résumé',nav:'Résumé'},
  pehchaan:{path:'teaching/pehchaan/',title:'Pehchaan Teaching Internship'},
  observation:{path:'teaching/observation/',title:'School Observation at Amity'},
  democracy:{path:'teaching/democracy/',title:'Teaching Democracy: A Design Example'},
  admin:{path:'admin/',title:'Portfolio Studio'},
  '404':{path:'404.html',title:'Page Not Found'},
};
export const esc=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
export const safeUrl=s=>{try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}};
const arrow='<span aria-hidden="true">↗</span>';
const link=(base,route,label,cls='text-link')=>`<a class="${cls}" href="${base}${routes[route].path}">${label} ${arrow}</a>`;
const tag=s=>`<span class="tag">${esc(s)}</span>`;
const list=items=>`<ul class="plain-list">${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
const knownImages=Object.fromEntries(defaultContent.certificates.map((x,i)=>[x.image,`certificate-${i+1}.webp`]));
knownImages[defaultContent.profile.portrait]='portrait.webp';
export function imageUrl(url,base){return knownImages[url]?base+'assets/'+knownImages[url]:safeUrl(url)}
function img(url,alt,base,cls='',priority=false){const src=imageUrl(url,base);return src?`<img class="${cls}" src="${esc(src)}" alt="${esc(alt)}" width="${cls==='portrait'?1154:1400}" height="1400" ${priority?'fetchpriority="high"':'loading="lazy"'} decoding="async">`:''}
function heading(num,title,desc=''){
 const chapter=/^(0[1-5]) \/ (.+)$/.exec(num);
 const label=chapter?`<span class="chapter-number" aria-hidden="true">${chapter[1]}</span><span class="chapter-label">${chapter[2]}</span>`:num;
 return `<header class="page-heading${chapter?' chapter-heading':''}"><p class="eyebrow">${label}</p><h1>${title}</h1>${desc?`<p class="lead">${desc}</p>`:''}</header>`;
}
function sectionHead(num,title,aside=''){return `<div class="section-heading"><div><p class="eyebrow">${num}</p><h2>${title}</h2></div>${aside}</div>`}

export function header(route,base,c){return `<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="container header-inner"><a class="brand" href="${base}" aria-label="${esc(c.profile.name)} — Home"><span class="monogram" aria-hidden="true">KM<span>.</span></span><span class="brand-caption">${esc(c.profile.name)}<small>History & Social Science</small></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu <span class="menu-lines" aria-hidden="true"></span></button><div id="navigation" class="navigation-panel"><div class="navigation-top"><p id="navigation-title" class="eyebrow">Explore the portfolio</p><button class="menu-close" aria-label="Close navigation">Close <span aria-hidden="true">×</span></button></div><nav class="navigation-links" aria-label="Main navigation">${['profile','teaching','resources','credentials','resume'].map((r,i)=>`<a ${route===r || (r==='teaching'&&['pehchaan','observation','democracy'].includes(route))?'aria-current="page"':''} href="${base}${routes[r].path}"><span class="nav-index" aria-hidden="true">0${i+1}</span>${routes[r].nav}</a>`).join('')}<a class="nav-contact" ${route==='contact'?'aria-current="page"':''} href="${base}contact/">Let’s Connect ${arrow}</a></nav><p class="navigation-note">History. Inquiry. Possibility.</p></div></div></header>`}
export function footer(base,c){return `<footer class="site-footer"><div class="container footer-top"><div><a class="footer-name" href="${base}">${esc(c.profile.name)}</a><p>History. Inquiry. Possibility.</p></div><div><p class="eyebrow">Start a conversation</p><a class="email-link" href="mailto:${esc(c.profile.email)}">${esc(c.profile.email)} ${arrow}</a></div></div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} ${esc(c.profile.name)} · Teaching portfolio</span><div>${link(base,'resume','Résumé')}${link(base,'admin','Owner sign in')}</div></div></footer>`}
function qualificationRows(c){return c.qualifications.map(q=>`<article class="qualification"><p class="period">${esc(q.period)}</p><div><h3>${esc(q.title)}</h3><p>${esc(q.place)}</p>${q.note?`<p class="small">${esc(q.note)}</p>`:''}${q.expected?`<p class="small">Expected completion: ${esc(q.expected)}</p>`:''}</div><span class="status ${/progress/i.test(q.status)?'progress':''}">${esc(q.status)}</span></article>`).join('')}
function practiceRows(c){return `<div class="practice-grid">${c.practice.map((p,i)=>`<article><span class="index-number">${String(i+1).padStart(2,'0')}</span><h3>${esc(p.title)}</h3><p>${esc(p.text)}</p></article>`).join('')}</div>`}
function experienceRows(c,base){return c.experiences.map((e,i)=>`
 <article class="experience-row" data-category="${esc(e.category||'Teaching')}">
  <div class="experience-meta"><span class="index-number" aria-hidden="true">${String(i+1).padStart(2,'0')}</span><p class="experience-date">${esc(e.period)}</p><span class="experience-type">${esc(e.type)}</span></div>
  <div class="experience-body"><p class="experience-status">${esc(e.status===e.period?'':e.status||'')}</p><h3>${esc(e.title)}</h3>${e.summary?`<p>${esc(e.summary)}</p>`:''}<details class="experience-details"><summary>Activities & learning</summary>${list(e.points||[])}</details>${['pehchaan','observation'].includes(e.id)?link(base,e.id,'Explore the experience'):''}</div>
 </article>`).join('')}

function certificateCard(c,base,index){return `
 <article class="certificate-card" data-category="${esc(c.category||'Other')}">
  <a class="certificate-image" href="${esc(safeUrl(c.image))}" target="_blank" rel="noopener noreferrer" aria-label="Open ${esc(c.title)} certificate in a new tab">${img(c.image,c.title+' — certificate',base)}</a>
  <div class="certificate-body"><div class="record-label"><span class="record-number" aria-hidden="true">${String(index+1).padStart(2,'0')}</span><p class="eyebrow">${esc(c.category||'Credential')}</p></div><h3>${esc(c.title)}</h3>
   <dl class="record-meta">${c.issuer?`<div><dt>Issued by</dt><dd>${esc(c.issuer)}</dd></div>`:''}${c.date?`<div><dt>Date</dt><dd>${esc(c.date)}</dd></div>`:''}</dl>
   <p>${esc(c.description||'')}</p><a class="text-link" href="${esc(safeUrl(c.image))}" target="_blank" rel="noopener noreferrer">View certificate ${arrow}<span class="sr-only">: ${esc(c.title)} (new tab)</span></a>
  </div>
 </article>`}

function resourceRows(c){return c.resources.map((r,i)=>`<article class="resource-row" data-category="${esc(r.category||'Teaching material')}"><span class="resource-number" aria-hidden="true">${String(i+1).padStart(2,'0')}</span><div class="resource-body"><p class="eyebrow">${esc(r.category||'Teaching material')}</p><h3>${esc(r.title)}</h3><p>${esc(r.description||'')}</p></div><a class="text-link" href="${esc(safeUrl(r.url))}" target="_blank" rel="noopener noreferrer">Open file ${arrow}<span class="sr-only">: ${esc(r.title)} (new tab)</span></a></article>`).join('')}


function schoolProgression(c,base) {
 if(!c.experiences.length)return '';
 return '<section class="container section school-experience" aria-labelledby="school-experience-title"><div class="section-heading"><div><p class="eyebrow">Teaching in practice</p><h2 id="school-experience-title">Growing through the classroom.</h2></div>'+link(base,'teaching','Explore the teaching record')+'</div><p class="experience-lead">Teaching, observation and reflection from my developing practice.</p><ol class="school-stages" role="list">'+c.experiences.map(e=>'<li class="school-stage '+(e.status==='Ongoing'?'current-stage':'')+'"><p class="stage-duration">'+esc(e.duration||'—')+' <span>'+esc(e.durationUnit||'Experience')+'</span></p><h3>'+esc(e.type||e.category)+'<span class="stage-status">'+esc(e.status||'')+'</span></h3><p class="stage-school">'+esc(e.institution||e.title)+'</p><p class="small">'+esc(e.summary||e.period)+'</p>'+(['pehchaan','observation'].includes(e.id)?link(base,e.id,'Read the experience'):link(base,'teaching','View the record'))+'</li>').join('')+'</ol></section>';
}
function hiringSummary(c,base){return '<section class="container hiring-summary" aria-labelledby="hiring-title"><div class="hiring-intro"><p class="eyebrow">For schools & recruiters</p><h2 id="hiring-title">The essentials,<br> <em>at a glance.</em></h2><p>'+esc(studySummary(c))+'.</p><div class="hiring-links">'+link(base,'resume','Résumé / save PDF')+link(base,'credentials','Supporting credentials')+'</div></div><dl class="hiring-facts">'+recruiterFacts(c).map(([label,value])=>'<div><dt>'+esc(label)+'</dt><dd>'+esc(value)+'</dd></div>').join('')+'</dl><p class="hiring-note">Classes and boards describe my teaching interests; the records below document my experience and qualifications.</p></section>';}
function optionalProfileFacts(c){return recruiterFacts(c).filter(([key])=>['Based in','Work preferences','Target classes','Boards of interest'].includes(key)).map(([label,value])=>'<p><strong>'+esc(label)+':</strong> '+esc(value)+'</p>').join('');}
function evidenceLinks(base){return '<nav class="evidence-links" aria-label="Explore teaching evidence">'+link(base,'democracy','Illustrative lesson design')+link(base,'credentials','Certificates & presentation')+'</nav>';}

function opening(c,base) {
 const p=c.profile;
 const ongoing=c.experiences.find(e=>e.status==='Ongoing' && /internship/i.test(e.type+' '+e.title));
 const status=ongoing?'Currently developing through school internship':c.qualifications.some(q=>q.title==='B.Ed.' && /progress/i.test(q.status))?'Currently developing through teacher education':'';
 return `<section class="hero opening-hero" aria-labelledby="opening-name"><div class="opening-traces" aria-hidden="true"><span></span><span></span><span></span></div><div class="container opening-inner"><div class="hero-copy"><p class="eyebrow opening-label" data-hero-step="1">History & Social Science · Educator</p><h1 id="opening-name" data-hero-step="2"><span>${esc(p.name.split(' ')[0])}</span><em>${esc(p.name.split(' ').slice(1).join(' '))}</em></h1><p class="hero-statement" data-hero-step="3">${esc(p.headline)}</p><div class="actions" data-hero-step="6">${link(base,'teaching','Explore My Teaching','button primary')}${link(base,'resume','View Résumé','button secondary')}</div><p class="hero-detail">${esc(studySummary(c))}<span>Available to join from ${esc(p.availability)}</span></p></div><div class="opening-visual"><span class="visual-reference" aria-hidden="true">01 / THE EDUCATOR</span><figure class="portrait-frame" data-hero-step="4"><div class="portrait-window">${img(p.portrait,'Portrait of '+p.name,base,'portrait',true)||'<div class="portrait-placeholder">Portrait<br>forthcoming</div>'}</div><figcaption><span>Curiosity is where<br><strong>understanding begins.</strong></span><span class="portrait-mark" aria-hidden="true">↗</span></figcaption></figure><p class="visual-annotation" data-hero-step="7" aria-hidden="true">Question · Explore · Reflect</p></div><div class="opening-bottom">${status?`<p class="opening-status" data-hero-step="5"><span class="status-dot" aria-hidden="true"></span>${esc(status)}</p>`:'<p class="opening-status" data-hero-step="5">History. Inquiry. Possibility.</p>'}<a class="opening-continue" href="#portfolio-start">Continue to the portfolio <span aria-hidden="true">↓</span></a></div></div></section><div id="portfolio-start" class="opening-transition" tabindex="-1"><span aria-hidden="true">The portfolio / Inquiry into practice</span></div>`;
}

export function view(route,c,base='./') {
 const p=c.profile;
 const pehchaan=c.experiences.find(e=>e.id==='pehchaan');
 const observation=c.experiences.find(e=>e.id==='observation');
 if((route==='pehchaan'&&!pehchaan)||(route==='observation'&&!observation))return view('404',c,base);
 switch(route){
 case 'home': return `${opening(c,base)}${hiringSummary(c,base)}${schoolProgression(c,base)}<section class="approach-section"><div class="container section">${sectionHead('02 / My approach','Less recall. More reasoning.')}${practiceRows(c)}${link(base,'democracy','See a teaching design example')}</div></section><section class="container closing-section"><p class="eyebrow">A developing educator, a considered approach</p><h2>Good teaching starts<br>with a good <em>question.</em></h2>${link(base,'contact','Let’s start a conversation','button primary')}</section>`;
 case 'profile':return `<div class="container">${heading('01 / Profile','A student of History.<br><em>A teacher in the making.</em>',esc(p.summary))}<section class="profile-split section compact"><div class="prose"><h2>Connecting the past<br>with the classroom.</h2><p>${esc(c.about)}</p><p>${esc(c.preparation)}</p><p>${esc(studySummary(c))}. The education record below lists institutions, progress and expected completion.</p></div><aside class="profile-facts" data-motion="fade-left"><p class="eyebrow">Professional focus</p><h3>History & Social Science</h3><p>Economics through academic study; English as my second B.Ed. pedagogy with internship teaching exposure.</p><hr><p class="eyebrow">Roles of interest</p>${p.roles.map(tag).join('')}<p class="small">${esc(studySummary(c))}.</p><hr><p class="eyebrow">Eligibility & availability</p><p>${esc(p.eligibility)}<br>Available from ${esc(p.availability)}</p>${optionalProfileFacts(c)}<hr><p class="eyebrow">Languages</p><p>${p.languages.map(esc).join(' · ')}</p></aside></section><section class="section">${sectionHead('Academic journey','Education, with status made clear.')}${qualificationRows(c)}</section><section class="section">${sectionHead('Skills & competencies','The tools behind my teaching.')}<div class="skill-list">${c.competencies.map(tag).join('')}</div></section></div>`;
 case 'teaching':return `<div class="container">${heading('02 / Teaching journey','Learning to teach.<br><em>Teaching to understand.</em>','School internships, community teaching, observation and the ideas I am developing through them.')}${evidenceLinks(base)}<div class="collection-tools" data-enhancement hidden><label>Find teaching experience<input id="experience-search" type="search" placeholder="Search school, activity or date" aria-controls="experience-list"></label><div class="filters" role="group" aria-label="Filter teaching experience">${['All','Teaching','Observation'].map((s,i)=>`<button class="filter" data-experience-filter="${s}" aria-pressed="${i===0}">${s}</button>`).join('')}</div></div><p id="experience-count" class="collection-count" role="status" data-enhancement hidden></p><section id="experience-list" class="experience-timeline" aria-label="Teaching and observation record">${experienceRows(c,base)}</section><p id="experience-empty" class="empty-note" ${c.experiences.length?'hidden':''}>No experiences match this search.</p><section class="section">${sectionHead('Teaching philosophy','Start with the learner.')}${practiceRows(c)}<div class="influence-row"><div><p class="eyebrow">Rabindranath Tagore</p><h3>Room for curiosity.</h3><p>Holistic education and creative learning remind me to keep History connected to the whole learner.</p></div><div><p class="eyebrow">Lev Vygotsky</p><h3>Support toward independence.</h3><p>Dialogue, guided source work and peer interaction help learners move toward independent historical reasoning.</p></div></div></section><section class="design-teaser"><div><p class="eyebrow">A teaching design example</p><h2>One concept.<br>Different pathways.</h2><p>How I would approach democracy through source work, discussion and visual interpretation.</p></div>${link(base,'democracy','Explore the example','button light')}</section></div>`;
 case 'pehchaan':return caseStudy(base,'Community teaching','Foundations first.<br><em>Confidence follows.</em>',pehchaan,`<h2>The teaching context</h2><p>The five-week NTCC internship at Pehchaan The Street School involved foundational literacy and numeracy with Nursery, LKG and UKG learners. Adult-literacy sessions through ULLAS extended the experience to five adult learners.</p><h2>What I contributed</h2>${list(pehchaan?.points||[])}<h2>What the experience developed</h2><p>Working with early learners gave me practical experience in activity-based methods, classroom management and community engagement. It connected teacher-education theory with the everyday work of explaining, practising and checking understanding.</p><h2>My next teaching step</h2><p>I want to carry a clear cycle into future lessons: notice what learners can already do, make the next idea visible, invite practice and use responses to plan the next step.</p>`, `<div class="evidence-aside" data-motion="fade"><p class="eyebrow">Documented experience</p><p>80 hours of community engagement at Pehchaan The Street School.</p><p>Certified as an on-ground intern / teacher.</p>${img(c.certificates.find(x=>x.image.includes('1787898375320'))?.image||defaultContent.certificates[1].image,'Pehchaan internship certificate',base)}${link(base,'credentials','View supporting credentials')}</div>`);
 case 'observation':return caseStudy(base,'School observation','The classroom<br><em>as a place to learn.</em>',observation,`<h2>Observation, with purpose</h2><p>The one-week observation internship at Amity International School, Mayur Vihar focused on History and Social Science classrooms. This was an observation placement, with attention to how lessons work in practice.</p><h2>What I paid attention to</h2>${list(observation?.points||[])}<h2>Beyond the lesson</h2><p>School culture, infrastructure and co-curricular integration offered a wider view of the learning environment. Classroom practice sits within that larger context.</p><h2>How it informs my practice</h2><p>I use reflection to connect what I observe with teacher-education theory: what happened, what supported participation and what I would consider when planning my own lesson.</p>`,`<aside class="note-panel"><p class="eyebrow">An observation lens</p><ol><li><strong>Questions</strong><p>How is thinking made visible?</p></li><li><strong>Participation</strong><p>Who is engaging, and how?</p></li><li><strong>Routines</strong><p>What gives the lesson structure?</p></li></ol></aside>`);
 case 'democracy':return `<div class="container">${heading('Teaching design / Illustrative approach','Democracy.<br><em>More than a definition.</em>','A proposed classroom approach adapted from my teaching philosophy. This is a design example, not a report of a delivered lesson.')}<div class="case-layout"><article class="prose"><h2>The shared learning intention</h2><p>Help learners explain democracy, consider different perspectives and support their understanding with evidence.</p><h2>Begin with a question</h2><p class="pull-quote" data-motion="fade-right">“How do people get a voice in the decisions that affect them?”</p><p>Invite initial ideas, clarify key vocabulary and connect the discussion to the concept of democracy.</p><h2>Offer different pathways</h2><div class="pathway"><span class="index-number">01</span><h3>Read, compare, discuss.</h3><p>Use reference materials, contrasting perspectives and primary sources. Offer guided prompts and extend the task through comparison and debate.</p></div><div class="pathway"><span class="index-number">02</span><h3>Look, interpret, explain.</h3><p>Use paintings, photographs or video to make an abstract idea tangible. Ask learners to explain what a visual source suggests and support their interpretation.</p></div><h2>Check for understanding</h2><p>Ask learners to explain the concept with an example and a reason. Use their responses to identify where a new explanation, further scaffolding or extension is needed.</p><h2>Reflect and adjust</h2><p>Consider whether both routes supported the same depth of understanding, and what should change in the next lesson.</p></article><aside class="note-panel"><p class="eyebrow">Planning lens</p><h3>Same intention.<br>Flexible support.</h3><p>Scaffold vocabulary and source reading. Offer spoken, written and visual ways to explain. Extend with a deeper comparison.</p><hr><p class="small">A full lesson plan and student assessment evidence have not yet been published.</p>${link(base,'resources','Browse available resources')}</aside></div></div>`;
 case 'resources':return `<div class="container">${heading('03 / Resource library','Ideas into practice.<br><em>Evidence into view.</em>','Teaching designs, supporting documents and resources from my developing practice.')}<section class="resource-feature"><div><p class="eyebrow">Teaching design · Social Science</p><h2>Teaching democracy<br>through different pathways.</h2><p>A web-readable example of planning for a shared outcome through source analysis, discussion and visual interpretation.</p>${link(base,'democracy','Read the design example')}</div><div class="resource-index"><span>01</span><p>QUESTION<br>EXPLORE<br>EXPLAIN<br>REFLECT</p></div></section><section class="section resource-library">${sectionHead('Downloads','Teaching files.')}<label class="collection-search" data-enhancement hidden>Search teaching files<input id="resource-search" type="search" placeholder="Search title, category or description" aria-controls="resource-list"></label><div class="filters" data-enhancement hidden role="group" aria-label="Filter resources">${['All','Lesson plan','Teaching material','Assessment','Presentation'].map((s,i)=>`<button class="filter" data-filter="${esc(s)}" aria-pressed="${i===0}">${esc(s)}</button>`).join('')}</div><p class="collection-count" id="resource-count" role="status">${c.resources.length} ${c.resources.length===1?'file':'files'} in the library</p><div id="resource-list">${resourceRows(c)}</div><p id="resource-empty" class="empty-note" ${c.resources.length?'hidden':''}>${c.resources.length?'No files in this category yet.':'Lesson plans and assessment files have not yet been published. The teaching design above and internship credentials are available to explore.'}</p></section>${c.gallery.length?`<section class="section">${sectionHead('Gallery','Moments from practice.')}<div class="gallery-grid">${c.gallery.map(g=>`<figure>${img(g.image,g.title,base)}<figcaption>${esc(g.title)}</figcaption></figure>`).join('')}</div></section>`:''}</div>`;
 case 'credentials':return `<div class="container">${heading('04 / Credentials','The work.<br><em>The record.</em>','Academic achievement, teaching experience and professional learning, with supporting documents.')}<section class="presentation-callout"><p class="eyebrow">Research & presentation · March 2026</p><h2>Rootedness in India.</h2><p>Co-author and presenter on NEP 2020 and Indian Knowledge Systems in teacher education, at the international seminar organised by Amity Institute of Education.</p></section><section class="section"><div class="collection-tools" data-enhancement hidden><label>Find a credential<input id="credential-search" type="search" placeholder="Search title, issuer or date" aria-controls="credential-list"></label><div class="filters" role="group" aria-label="Filter credentials">${['All',...new Set(c.certificates.map(x=>x.category||'Other'))].map((s,i)=>`<button class="filter" data-credential-filter="${esc(s)}" aria-pressed="${i===0}">${esc(s)}</button>`).join('')}</div></div><p id="credential-count" class="collection-count" role="status" data-enhancement hidden></p><p id="credential-empty" class="empty-note" hidden>No credentials match this search.</p><div class="certificate-grid" id="credential-list">${c.certificates.map((x,i)=>certificateCard(x,base,i)).join('')}</div>${c.certificates.length?'':'<p class="empty-note">No credentials are currently published.</p>'}</section></div>`;
 case 'resume':return `<div class="container resume-page">${heading('Résumé / Professional overview',esc(p.name),'History & Social Science · Emerging educator')}<div class="actions print-actions"><button class="button primary" id="print-resume">Print / save as PDF <span aria-hidden="true">↓</span></button>${p.cv&&safeUrl(p.cv)?`<a class="button secondary" href="${esc(safeUrl(p.cv))}" target="_blank" rel="noopener noreferrer">Download CV ${arrow}</a>`:''}${link(base,'contact','Contact')}</div><p><a href="mailto:${esc(p.email)}">${esc(p.email)}</a> · ${p.languages.map(esc).join(' · ')}</p><section class="resume-section"><h2>Professional profile</h2><p>${esc(p.summary)}</p><p>Roles of interest: ${p.roles.map(esc).join('; ')}. ${esc(studySummary(c))}.</p><p><strong>${esc(p.eligibility)}</strong> · Available to join from <strong>${esc(p.availability)}</strong>.</p></section><section class="resume-section"><h2>Location & teaching interests</h2>${optionalProfileFacts(c)}</section><section class="resume-section"><h2>Education</h2>${qualificationRows(c)}</section><section class="resume-section"><h2>Teaching & observation</h2>${c.experiences.map(e=>`<article><h3>${esc(e.title)}</h3><p class="small">${esc(e.period)} · ${esc(e.type)}</p>${list(e.points||[])}</article>`).join('')}</section><section class="resume-section"><h2>Skills</h2><p>${c.competencies.map(esc).join(' · ')}</p></section><section class="resume-section"><h2>Professional learning & presentation</h2>${c.certificates.filter(x=>['Presentation','Professional learning'].includes(x.category)).map(x=>`<p><strong>${esc(x.title)}</strong><br>${esc(x.description)}<br><span class="small">${esc(x.issuer)} · ${esc(x.date)}</span></p>`).join('')}</section></div>`;
 case 'contact':return `<div class="container">${heading('05 / Contact','A conversation<br><em>about what comes next.</em>','For teaching opportunities, school internships and conversations about History and Social Science education.')}<div class="contact-layout"><section><p class="eyebrow">Email me directly</p><a class="contact-email" href="mailto:${esc(p.email)}">${esc(p.email)} ${arrow}</a><button class="text-link copy-email" data-email="${esc(p.email)}">Copy email address</button><p id="copy-status" role="status"></p><div class="contact-note"><p class="eyebrow">Available from ${esc(p.availability)}</p><p>${esc(p.eligibility)} · ${esc(studySummary(c))}.</p>${optionalProfileFacts(c)}<p class="eyebrow">For schools & recruiters</p><p>Please include the school name, subject, classes to be taught, location and proposed joining timeline.</p>${link(base,'resume','View my résumé')}</div></section><form id="contact-form" class="contact-form"><h2>Prepare an introduction.</h2><p>This opens your email app with a draft. You can review it before sending.</p><label>Your name<input name="name" autocomplete="name" required maxlength="100"></label><label>Your email<input type="email" name="email" autocomplete="email" required maxlength="200"></label><label>School / organisation<input name="school" autocomplete="organization" maxlength="150"></label><label>Your message<textarea name="message" rows="5" required maxlength="3000"></textarea></label><button class="button primary" type="submit">Open email draft ${arrow}</button><p id="contact-status" role="status"></p></form></div></div>`;
 case 'admin':return `<div class="container admin-page">${heading('Owner workspace','Portfolio Studio.','Update your profile, teaching experience and files. Changes go live only when you publish.')}<div id="studio"><form id="login-form" class="contact-form"><h2>Owner sign in</h2><label>Email<input name="email" type="email" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><button class="button primary" type="submit">Sign in</button><p id="login-status" role="status"></p></form></div></div>`;
 default:return `<div class="container not-found">${heading('404 / Page not found','A page out of place.','The link may have changed. Return to the portfolio to find the right chapter.')}${link(base,'home','Back to the portfolio','button primary')}</div>`;
 }
}
function caseStudy(base,label,title,exp,body,aside){return `<div class="container"><div class="breadcrumb">${link(base,'teaching','Teaching journey')}</div>${heading(label,title,esc(exp?.title||''))}<div class="case-meta"><span>${esc(exp?.period||'')}</span><span>${esc(exp?.type||'')}</span></div><div class="case-layout"><article class="prose">${body}</article>${aside}</div></div>`}
