import {homeView,profileView,teachingView,resourcesView,credentialsView,resumeView,contactView,galleryView} from './editorial.js?v=editorial-20261004';
import {esc,heading,link,list,img,imageUrl} from './view-helpers.js?v=editorial-20261004';
import {democracyView,documentUrl} from './evidence.js?v=editorial-20261004';
import {philosophySection} from './teaching-philosophy.js?v=editorial-20261004';
import {observationJournal,amityDays} from './amity-journal.js?v=editorial-20261004';
import {publicContent} from './content.js?v=editorial-20261004';
import {galleryRecord,photoBackdrop,photoPlate,pageAtmosphere,studyInterval} from './page-media.js?v=editorial-20261004';
export {routes,esc,safeUrl,imageUrl} from './view-helpers.js?v=editorial-20261004';
export {header,footer} from './editorial.js?v=editorial-20261004';

export function view(route,c,base='./'){
 const published=publicContent(c);
 const backgroundRoute=['pehchaan','observation'].includes(route)&&!published.experiences.some(x=>x.id===route)?'404':route;
 return pageAtmosphere(published,backgroundRoute,base)+pageView(route,route==='admin'?c:published,base);
}
function pageView(route,c,base){
 const pages={home:homeView,profile:profileView,resources:resourcesView,credentials:credentialsView,resume:resumeView,contact:contactView,gallery:galleryView,democracy:democracyView};
 if(pages[route])return pages[route](c,base);
 if(route==='teaching')return teachingView(c,base,philosophySection);
 if(route==='admin')return `<div class="container admin-page distinctive-page"><header class="studio-welcome"><div><p class="eyebrow">Owner workspace</p><h1>Portfolio Studio</h1><p class="lead">Update your profile, teaching experience and files. Changes go live only when you publish.</p></div>${img(c.profile.portrait,'Portrait of '+c.profile.name,base,'contact-avatar')}</header><div id="studio"><form id="login-form" class="studio-signin-card"><h2>Owner Sign In</h2><label>Email<input name="email" type="email" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><button class="button primary" type="submit">Sign in</button><p id="login-status" role="status"></p><p class="small">Changes go live only when you publish.</p></form></div></div>`;
 if(['pehchaan','observation'].includes(route)){
  const e=c.experiences.find(x=>x.id===route);if(!e)return pageView('404',c,base);
  const community=route==='pehchaan';
  const journal=community?null:observationJournal(c);
  const photo=community?c.gallery.find(x=>x.id==='pehchaan-collage'):journal?{image:'assets/evidence/amity-journal/campus.webp',title:'Amity International School, Mayur Vihar',description:'School photograph from the supplied observation journal'}:null;
  const report=c.resources.find(x=>x.id==='ntcc-community-report');
  const certificate=community?c.certificates.find(x=>x.category==='Teaching'&&/pehchaan/i.test(x.issuer||'')):null;
  const journalUrl=journal?documentUrl(journal.url,base):'';
  const daily=journal?'<h2>The four-day record</h2><div class="observation-days">'+amityDays.map((day,i)=>'<section class="observation-day"><p class="eyebrow">Day '+(i+1)+' · '+esc(day.date)+'</p><h3>'+esc(day.title)+'</h3><p>'+esc(day.text)+'</p><a class="text-link" href="'+esc(journalUrl)+'#page='+[4,6,8,10][i]+'">Journal pages '+esc(day.pages)+' <span aria-hidden="true">→</span></a></section>').join('')+'</div>':'';
  const supporting=community?'<h2>Supporting documents</h2><p>The completion certificate confirms 80 hours as an on-ground intern / teacher. The published NTCC report contains weekly reflections and annexures, and records the community work and ULLAS adult-literacy component.</p>':journal?daily+'<h2>What I learned</h2><p>The journal compares lecture-based explanation with examples, discussion and practical tasks. Its reflections consider classroom management, reading habits, student responsibility and the support teachers provide through counselling and school activities.</p>':'<h2>Areas of attention</h2><p>The experience record identifies questioning, participation and classroom routines as areas of attention.</p>';
  const evidence=community?(certificate?'<a href="'+esc(imageUrl(certificate.image,base))+'" data-viewer data-title="'+esc(certificate.title)+'">'+img(certificate.image,'Pehchaan certificate confirming 80 hours as an on-ground intern / teacher',base,'case-evidence-img')+'</a>'+link(base,'credentials','View supporting credentials'):'<p>A completion certificate is not currently published.</p>')+(report?'<a class="button primary" href="'+esc(documentUrl(report.url,base))+'" data-viewer data-title="'+esc(report.title)+'">Read the NTCC report →</a>':''):journal?'<a class="journal-preview" href="'+esc(journalUrl)+'" data-viewer data-title="'+esc(journal.title)+'" aria-label="Read '+esc(journal.title)+'">'+img(journal.thumbnail,'Cover of the Amity school observation reflective journal',base,'case-evidence-img')+'</a><p>'+esc(journal.type)+' · '+esc(journal.evidenceStatus)+'</p><a class="button primary" href="'+esc(journalUrl)+'" data-viewer data-title="'+esc(journal.title)+'">Read reflective journal →</a><a class="text-link" href="'+esc(journalUrl)+'" download="amity-observation-reflective-journal.pdf">Download journal PDF ↓</a><p class="small">Rebuilt from the supplied handwritten notes and photographs. Dates follow the journal; its year is not recorded.</p>':'<p>A reflective journal or mentor record is not currently published.</p>';
  const cover=community?`<header class="community-cover"><div><p class="eyebrow">Community teaching · Pehchaan</p><h1>Foundational Literacy &amp; Numeracy</h1><p class="lead">${esc(e.title)}</p>${link(base,'resources','Read the supporting reports')}</div>${photoPlate(photo,base,'community-cover-photo',true)}</header>`:`<header class="observation-cover">${photoBackdrop(photo,base)}<div><p class="eyebrow">A school observation journal</p><h1>Learning Through Classroom Observation</h1><p class="lead">${esc(e.title)}</p></div></header>`;
  const strip=journal?`<div class="journal-photo-strip" aria-label="Photographs from the observation journal">${[['junior-library','Junior library'],['computer','Computer laboratory'],['assembly','School assembly']].map(([id,title])=>photoPlate({image:'assets/evidence/amity-journal/'+id+'.webp',title,context:'From the supplied observation journal'},base)).join('')}</div>`:'';
  return `<div class="container case-page distinctive-page ${community?'community-page':'observation-page'}"><div class="breadcrumb">${link(base,'teaching','Teaching journey')}</div>${cover}<div class="case-meta"><span>${esc(e.period)}</span><span>${esc(e.type)}</span><span class="status">${esc(e.status)}</span></div>${strip}${studyInterval(base,community?'english':'teaching',community?'economics':'history',community?'notes':'shelf')}<div class="case-layout"><article class="prose case-record"><h2>${community?'The teaching context':'The observation context'}</h2><p>${esc(e.summary||'')}</p><h2>Activities recorded</h2>${community?'<div class="community-activities">'+(e.points||[]).map((point,i)=>'<section><span class="icon-disc" aria-hidden="true">'+String(i+1)+'</span><p>'+esc(point)+'</p></section>').join('')+'</div>':list(e.points||[])}${supporting}${e.reflection?'<h2>My reflection</h2><p>'+esc(e.reflection)+'</p>':''}</article><aside class="evidence-aside"><p class="eyebrow">Supporting evidence</p><h2>${community?'Community teaching record':'Reflective journal'}</h2>${evidence}</aside></div>${studyInterval(base,'teaching','english','arc')}</div>`;
 }
 const material=galleryRecord(c,'tlm-documentation','mock-election-activity');
 return `<div class="container not-found distinctive-page"><div class="not-found-layout"><div><p class="eyebrow">404 / Page not found</p><h1>A page out of place.</h1><p class="lead">The link may have changed. Return to the portfolio to find the right chapter.</p><div class="actions">${link(base,'home','Back to Home','button primary')}${link(base,'resources','Explore Teaching Evidence','button secondary')}</div></div>${material?`<div class="misplaced-document" aria-hidden="true">${img(material.image,'',base)}</div>`:''}</div></div>`;
}
